### ISSUE TITLE
The implementation for real time rendering.

### ISSUE THREAD

**Issue by JunyuanDeng** [ingra14m/Deformable-3D-Gaussians#12]
Thanks for your great job!
I noticed that in readme.md, you said: "Also, thanks to @[ashawkey](https://github.com/ashawkey) for releasing the original GUI.". Could you indicate where is the "original GUI", I want to implement a similar version of real-time rendering.

Thanks for your coming reply!

**Comment by ingra14m** [comment]
Hi, thanks for your interest.

Actually, our real-time reviewer is adapted from the viewer in the [DreamGaussian](https://github.com/dreamgaussian/dreamgaussian) proposed by @[ashawkey](https://github.com/ashawkey). We plan to release the source code along with the real-time viewer on November 17th. If you really need it, just drop me an email.

**Comment by JunyuanDeng** [comment]
Thanks for your sincere reply, I will check that repo.
