### ISSUE TITLE
Dynerf training

### ISSUE THREAD

**Issue by pablodawson** [ingra14m/Deformable-3D-Gaussians#14]
Hey there,

Thanks for your work, I've been testing it and the results are great.
I saw that in your paper you did some tests on Dynerf. Would it be possible to know the code modifications for that?
Even it wouldn't have an advantage over other methods like you've stated, having it as a Gaussian representation would help a lot for my projects.

**Comment by pablodawson** [comment]
Nevermind, it supports it already!

**Comment by ingra14m** [comment]
I have some insights for this dataset. 
- I think the convergence of this dataset is highly related to the initialization of the point cloud. Randomly generated point clouds can lead to convergence failure. 
- For methods like ours that are based on a deformation field, long-capture poses challenges, so we default to reading the [first 24 frames](https://github.com/ingra14m/Deformable-3D-Gaussians/blob/55178d6dc947060bc7bef433d014591b4f54a88e/scene/__init__.py#L58). 
- Reading all the images at once can have a huge burden on VRAM, `--load2gpu_on_the_fly` can help you reduce memory consumption. 

The code for this dataset is only used to standardize the format of the dataset, and we haven't optimized for this dataset.

Thank you for your interset in our work!

**Comment by pablodawson** [comment]
Interesting, thanks for the tips!
I'll try generating a `points.npy` in COLMAP and integrating it to the codebase, will report back the results.
