### ISSUE TITLE
Question about how to get the initial point clouds under monocular setting

### ISSUE THREAD

**Issue by Torment123** [ingra14m/Deformable-3D-Gaussians#2]
Hi, the paper says that camera poses and sparse point cloud will be given as a result of SfM. However, as I understand it, monocular video sequence means for each time step, only a single image from one view is available, so there are no multi view images to do SfM. So could you help me understand how the SfM is performed under this condition and get the initial sparse point clouds? Thanks

**Comment by ingra14m** [comment]
Hi Torment123,

Thank you for your interest in our work. In our study, we tested both the HyperNeRF real dataset and the D-NeRF synthetic dataset. 

HyperNeRF (a real dataset with monocular video sequence) provides a points.npy file, which stores the coordinates of the point cloud. Based on the [preprocessing code](https://colab.research.google.com/github/google/nerfies/blob/main/notebooks/Nerfies_Capture_Processing.ipynb) from HyperNeRF, they directly employed colmap (actually for static scenes) to forcibly match the camera poses in dynamic scenes, subsequently generating a point cloud. Naturally, this camera pose estimation is imprecise, yet the authors of HyperNeRF managed to achieve relatively robust results in dynamic scenes using this approach. During our experimentation, we also observed that inaccurate camera poses significantly hinder the convergence of Deformable 3D Gaussians, which is an area we hope to improve upon in the future. 

For the D-NeRF dataset, we directly utilized random point clouds to initialize the 3D Gaussians.

**Comment by Torment123** [comment]
Thank you for the fast and detailed explanation, that helps a lot

**Comment by BerenChou** [comment]
Hi! Thank you for your great work and congratulate on your CVPR acceptance!

However, I have one question about how you initialize the point clouds for NeRF-DS. Did you simply use the points cloud from points.npy in NeRF-DS?

**Comment by ingra14m** [comment]
Thanks for your interest. In our experiments and the current code, we directly used the `points.npy` in NeRF-DS without any post-processing. I believe that in real-world scenarios, providing a more accurate and dense point cloud will definitely contribute to the learning and convergence of deformable-GS.
