### ISSUE TITLE
About evaluation with HyperNerf dataset

### ISSUE THREAD

**Issue by HaoZhiG** [ingra14m/Deformable-3D-Gaussians#33]
Hi! I'm currently working on training the interp_chickchicken scene in your project, and I encountered an issue during the evaluation using metrics.py. It seems that all the evaluation metrics are showing NAN, and upon further investigation, I noticed that the test folder generated during evaluation is missing image files in both the 'gt' and 'renders' directories. I was wondering if you could provide some guidance on what might be causing this issue and how I can resolve it. Any insights or suggestions you have would be greatly appreciated.
![image](https://github.com/ingra14m/Deformable-3D-Gaussians/assets/101928950/e81cd405-5b4b-4fac-9993-6659208b1284)

**Comment by ingra14m** [comment]
Very very sorry for the late reply. Have you run the render.py to render the test images using the following code:

```shell
python render.py -m outputs/your/path --skip_train
```

**Comment by HaoZhiG** [comment]
Thank you very much for your response. I have attempted to use render.py for rendering and then utilize metric.py for evaluation. However, it seems that during the rendering process, the test set cannot be rendered, thus hindering the evaluation process. I would be grateful for any guidance or suggestions you may have to address this issue.
![image](https://github.com/ingra14m/Deformable-3D-Gaussians/assets/101928950/6c38f5fa-28d1-45c1-9a95-5f12725e0e0a)

**Comment by ingra14m** [comment]
Hi, maybe, When you train the model, you did not use `--eval`? And don't forget that we organize the real-world dataset as [this format](https://github.com/ingra14m/Deformable-3D-Gaussians#:~:text=the%20datasets%20as-,follows,-%3A). It will affect the split of training and test set.

```shell
python train.py -s ...../HyperNeRF/misc/cookies -m output/hypernerf/cookies --eval
```

**Comment by HaoZhiG** [comment]
Thank you for your guidance. It turns out I didn't organize the dataset according to the specified format. The issue is resolved now. Your project is really cool, and I look forward to your another work (SC-GS).

**Comment by ingra14m** [comment]
Very glad that you solved this issue. We will release the code of SC-GS upon acceptance.

**Comment by xdh096** [comment]
> Thank you for your guidance. It turns out I didn't organize the dataset according to the specified format. The issue is resolved now. Your project is really cool, and I look forward to your another work (SC-GS).

I also encountered this problem, how should I organize the dataset，thank you！
