### ISSUE TITLE
About deformation Gaussians suddenly flew off

### ISSUE THREAD

**Issue by guanjunwu** [ingra14m/Deformable-3D-Gaussians#34]
Hello, I'm wondering if you've encountered a similar issue during optimization: Initially, the entire scene was converging normally, but midway through the training, some dynamic points suddenly flew off to a far distance, leading to a seemingly inexplicable failure in the training process.

I guess the problem mainly occurred from cuda?

**Comment by ingra14m** [comment]
I know this problem. Just reduce the learning rate of the deformation field.

**Comment by guanjunwu** [comment]
感谢老哥，虽然我也不知道为什么。。。
