### ISSUE TITLE
有关D-NERF数据集的疑问

### ISSUE THREAD

**Issue by ljcccccccccccccccccc** [ingra14m/Deformable-3D-Gaussians#53]
我打算训练D-Nerf，结果报错 File"D:\pythonProject\Deformable-30-Gaussians\scene\__init_py",line 64,in __init__  assert False,"could not recognize scene type!AssertionError:Could not recognize scene type!
在代码中检查发现是数据集的文件夹中没有特定的一些文件
![image](https://github.com/ingra14m/Deformable-3D-Gaussians/assets/138851235/ed8bff76-82a5-4486-9f0a-a35dbce6f87d)
我在想是不是我数据集下载的有错误，可能我问的问题很蠢，烦请作者解惑一下，谢谢

**Comment by czhstone** [comment]
可能是你的“-s”路径没有正确指向数据集，例如你想训练lego这个场景，要确保“-s”指向”/.../lego“

**Comment by haliphinx** [comment]
运行的时候 -s 后面的路径需要指向特定的testcase文件夹，比如D-Nerf/trex。通常d-nerf数据集下载下来文件结构就是正确的，可以确认该文件夹下应该有“transforms_train.json" 这个文件。也有可能是路径写的有问题，没有定位到需要的文件地址。

**Comment by ljcccccccccccccccccc** [comment]
原来如此，谢谢你，万分感谢

**Comment by ljcccccccccccccccccc** [comment]
> 运行的时候 -s 后面的路径需要指向特定的testcase文件夹，比如D-Nerf/trex。通常d-nerf数据集下载下来文件结构就是正确的，可以确认该文件夹下应该有“transforms_train.json" 这个文件。也有可能是路径写的有问题，没有定位到需要的文件地址。

成功了 万分感谢！
