### ISSUE TITLE
Training failure due to the scale difference between the offset and the canonical space gs

### ISSUE THREAD

**Issue by Time-Lord12th** [ingra14m/Deformable-3D-Gaussians#67]
Hello，
Thanks for your great work. Have you ever encountered training failure due to the scale difference between the offset and the canonical space gs?
For example, the position range of the canonical space gs is [-0.2, 0.2], while the offset range output by the deformation model is [-1, 1]. So most of the gs will be deformed out of the camera's field of view, causing a large difference between the rendered image and the ground truth, making it impossible for the model to optimize properly.
Do you have any opinion on this issue?

**Comment by ingra14m** [comment]
Hi, thanks for your interest.

I think this problem stems from the dataset and the non-constrained offset. 

- As for the dataset. In dataset with accurate camera poses, such as D-NeRF, I did not encounter this problem. But in the HyperNeRF/Nerfies dataset, I do noticed that many scenarios will fail to converge. The inaccurate camera poses (HyperNeRF) and lack of training viewpoint (Neu3D, forward-facing scenes with only 20 viewpoints and limited coverage) make it difficult for the learning of Deformation Field.
- Based on the insights mentioned above, I believe that adding constrains to the offset can counteract the bad influence on these dataset. I also believe that camera pose optimization will play an important role in real-world dynamic scene reconstruction.

**Comment by Time-Lord12th** [comment]
I will check my own dataset and add constrains to the offset, thanks for your advice!
