### ISSUE TITLE
Densification of gaussians

### ISSUE THREAD

**Issue by DevikalyanDas** [ingra14m/Deformable-3D-Gaussians#7]
Hello @ingra14m ,
Thank you for your great work and contribution. I want to know how the densification of Gaussians is carried out for monocular dynamic scenes. Are you densifying only the gaussian in the canonical space? Can you please share the code to my email : devikalyandas9067@gmail.com

Thanks

**Comment by xwx0924** [comment]
Hello @ingra14m ,
   +1 ，xwxxmu@gmail.com

Thanks

**Comment by ingra14m** [comment]
Hi @DevikalyanDas @xwx0924 , 

thank you for your interest in this work. 

Our method learns the 3D Gaussian in the canonical space and maps it to the standard world space through a deformation field. Based on the principle of gradient backpropagation, the gradients of the deformation field and the canonical 3D Gaussian are the same. The dynamic parts, having larger gradients, align very well with the Densification mechanism. Hence, we indeed only densify the 3D Gaussian in the canonical space. 

Lastly, we will open source our code on the submission deadline, as I don't want our work to appear like a follower. If you truly need the source code, please send me an email at [14ziyiyang@gmail.com](mailto:14ziyiyang@gmail.com).
