### ISSUE TITLE
Question about the rendering quality

### ISSUE THREAD

**Issue by BoMingZhao** [ingra14m/Deformable-3D-Gaussians#8]
Hi, first of all, thanks for your great work! 
While implementing it, I found that even when using the validation set as test data in the Lego dataset, I could only achieve a PSNR of 25.7. 
![00008](https://github.com/ingra14m/Deformable-3D-Gaussians/assets/26064261/c90aacab-4bfe-41d0-b487-a572afa804b2)
However, I noticed in your submodel that you mentioned expanding the fourth dimension of SH. Does this mean you used SH degree=4? I would greatly appreciate it if I could refer to your code! My email is bmzhao@zju.edu.cn. 

Thanks!

**Comment by ingra14m** [comment]
Hi, thank you for your interest in this work. 

Firstly, as I pointed out in the paper, the dataset for Lego is flawed. Using the validation set is merely to make the evaluation metrics meaningful. I would recommend you conduct experiments on other datasets from D-NeRF. 

Secondly, there seems to be some gap between your implementation and my version, as the interior of the Lego shovel is also blurry in yours. We will open source our code on the submission deadline, as I don't want our work to appear like a follower. 

Lastly, all our tests utilized the main branch of [depth-diff-gaussian-rasterization](https://github.com/ingra14m/depth-diff-gaussian-rasterization). 

Wish you success in your research.

**Comment by aartykov** [comment]
Hello!

Thanks for the great work @ingra14m. When are you going to open-source the code? On the deadline of CVPR(17.11.2023)?

Thanks in advance!

**Comment by ingra14m** [comment]
Hi @aartykov, thanks for your interest in our work. 

I indeed plan to release the full code on the CVPR submission deadline, as I don't want my work to appear like a follower. However, if you need the code from this work for some interesting applications, such as improving rendering quality or expanding for more applications, just drop me an email. I'd be more than happy to provide you with the source code.

**Comment by santaebagu** [comment]
HI @ingra14m :) I study NeRF. I think your research is really great! I'd like to study more, so please kindly provide me withe the source code. My email is santaebagu@naver.com.
Thank you so much!

**Comment by LeeHanmin** [comment]
Hello！
Hello. This is really an interesting job, I want to know more, if you can please send me an email and share the source code.
leehanmincloud@gmail.com

**Comment by ingra14m** [comment]
@santaebagu @LeeHanmin Done! Thanks for your interest.
