### ISSUE TITLE
How to get a depth map of a scene presented by 3d-gs

### ISSUE THREAD

**Issue by hdupuyang** [ingra14m/Deformable-3D-Gaussians#9]
thank for your great work. I'd like to know how to obtain a depth map from a scene presented by 3d-gs?
thanks

**Comment by ingra14m** [comment]
Hi, thanks for your interest in our work. 

If your want to obtain the depth from 3D-GS, you can refer to my [depth-diff-gaussian-rasterization](https://github.com/ingra14m/depth-diff-gaussian-rasterization).

For more information, you can refer to [this reply](https://github.com/graphdeco-inria/gaussian-splatting/pull/30#issuecomment-1741678199).
